services:
  - type: web
    name: fraud-detection-streamlit
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=$PORT --server.address=127.0.0.1
    plan: free
